import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { GetStaticProps } from 'next'

type Props = { timestamp: string }

export default function ISR(props: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ISRページ</h1>
        <p> time: {props.timestamp}</p>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  return {
    props: {
      timestamp: new Date().toISOString(),
    },
    revalidate: 1,
  }
}